/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Characters_Captain_Barbarossa.gltf -o src/Components/Captain.jsx -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Captain({hovered,...props}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Characters_Captain_Barbarossa.gltf')
  const { actions } = useAnimations(animations, group)
  console.log(actions);
  useEffect(()=>{
  const animations = hovered? "Sword":"Idle"
  actions[animations].reset().fadeIn(0.5).play();
  return ()=> actions[animations].fadeOut(0.5);
  },[hovered])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh name="Captain_Barbarossa_" geometry={nodes.Captain_Barbarossa_.geometry} material={materials.Atlas} skeleton={nodes.Captain_Barbarossa_.skeleton} />
          <skinnedMesh name="Ernest" geometry={nodes.Ernest.geometry} material={materials.Atlas} skeleton={nodes.Ernest.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Characters_Captain_Barbarossa.gltf')
