/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Characters_Matt.gltf -o src/Components/Matt.jsx -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Matt(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Characters_Matt.gltf')
  const { actions } = useAnimations(animations, group)
  console.log(actions);
  useEffect(()=> {
  actions["Wave"].reset().fadeIn(0.5).play();
  return () => actions["Wave"].fadeOut(0.5)
  }, [])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh name="Matt" geometry={nodes.Matt.geometry} material={materials.Atlas} skeleton={nodes.Matt.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Characters_Matt.gltf')
